// This file has been autogenerated from a class added in the UI designer.

using System;
using CustomPageSegmentedControl;
using Foundation;
using UIKit;

namespace Sample
{
	public partial class TableViewController : UITableViewController, IARSegmentControllerDelegate
	{
		string[] tableItems = new string[] { "Vegetables", "Fruits", "Flower Buds", "Legumes", "Bulbs", "Tubers",
		"Vegetables", "Fruits", "Flower Buds", "Legumes", "Bulbs", "Tubers","Vegetables", "Fruits", "Flower Buds", "Legumes", "Bulbs", "Tubers"
		,"Vegetables", "Fruits", "Flower Buds", "Legumes", "Bulbs", "Tubers"};
		string CellIdentifier = "TableCell";

		public string SegmentTitle {
			get {
				return "Sample";
			}
		}

		public TableViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			//this.NavigationController.NavigationBarHidden = true;
		}

		public override nint RowsInSection(UITableView tableview, nint section)
		{
			return tableItems.Length;
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell = tableView.DequeueReusableCell(CellIdentifier);
			string item = tableItems[indexPath.Row];

			//---- if there are no cells to reuse, create a new one
			if (cell == null) { cell = new UITableViewCell(UITableViewCellStyle.Default, CellIdentifier); }

			cell.TextLabel.Text = item;

			return cell;
		}
	}
}
